# Fluent Bit 설정을 위한 values.yaml - filter 부분 추가해야 함 (특정 네임스페이스)
serviceAccount:
  create: false
  name: fluent-bit

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

config:
  service: |
    [SERVICE]
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
  filters: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL           https://kubernetes.default.svc:443
        Kube_CA_File       /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log          On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off
        
    [FILTER]
        Name                grep
        Match               kube.*
        Regex              $kubernetes['namespace_name'] ^sample-app$
        
  outputs: |
    [OUTPUT]
        Name                cloudwatch_logs
        Match               kube.*
        region             ap-northeast-2
        log_group_name     /aws/eks/hello-dev-cluster/applications
        log_stream_prefix  ${kubernetes.namespace_name}.${kubernetes.pod_name}.
        auto_create_group  true
        log_retention_days 30
  customParsers: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true