# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # 클러스터 기본 설정
  name: hello-dev-cluster     # 클러스터 이름 - 이 이름으로 EKS 클러스터가 생성됨
  region: ap-northeast-2      # 서울 리전
  version: "1.27"            # 쿠버네티스 버전 - 최신 안정 버전 사용

# VPC 네트워크 설정
vpc:
  cidr: "192.168.0.0/16"     # VPC의 IP 주소 범위
  nat:
    gateway: Single          # NAT Gateway 설정 - 비용 절감을 위해 Single 사용
    # HA가 필요한 경우 HighlyAvailable로 변경 가능

# 클러스터 접근 설정
privateCluster:
  enabled: false            # 프라이빗 클러스터 비활성화 (퍼블릭 접근 허용)

# IAM 설정
iam:
  withOIDC: true            # OIDC 인증 활성화 - AWS IAM과 쿠버네티스 서비스 계정 연동에 필요
  serviceAccounts:          # 클러스터에서 사용할 서비스 계정들
    # ALB 인그레스 컨트롤러용 서비스 계정
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::897722706632:policy/AWSLoadBalancerControllerIAMPolicy"

    # EBS CSI 드라이버용 서비스 계정
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      attachPolicyARNs:
        - "arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"

# 노드 그룹 설정
managedNodeGroups:
  - name: hello-dev-ng      # 노드 그룹 이름
    instanceType: t3.medium # 인스턴스 타입 - 개발 환경에 적합한 크기
    minSize: 1             # 최소 노드 수
    maxSize: 3             # 최대 노드 수 - 부하에 따라 자동 스케일링
    desiredCapacity: 1     # 초기 노드 수
    volumeSize: 20         # 각 노드의 디스크 크기(GB)

    # SSH 접속 설정
    ssh:
      allow: true                # SSH 접속 허용
      publicKeyName: eks-test-key  # 이전에 생성한 키 페어 이름

    # 노드 레이블과 태그
    labels:
      role: worker
      environment: development
    tags:
      environment: development

    # 노드 업데이트 설정
    updateConfig:
      maxUnavailable: 1    # 동시에 업데이트할 수 있는 최대 노드 수

# 필수 애드온 설정
addons:
  - name: vpc-cni         # 컨테이너 네트워킹
    version: latest
  - name: coredns        # DNS 서비스
    version: latest
  - name: kube-proxy     # 네트워크 프록시
    version: latest
  - name: aws-ebs-csi-driver  # EBS 볼륨 관리
    version: latest

# CloudWatch 로깅 설정
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]